name: "Scully Publish"
description: "Build and deploy your Scully site to GitHub Pages."
branding:
  icon: "book-open"
  color: "red"
inputs:
  access-token:
    description: "A personal access token needed to push your site after it has been built."
    required: true
  deploy-branch:
    description: "The branch expected by GitHub to have the static files needed for your site."
    required: false
    default: "master"
  install-args:
    description: "Additional arguments that get passed to `npm ci` (e. g. `--legacy-peer-deps`)."
    required: false
    default: ""
  build-args:
    description: "Additional arguments that get passed to `npm run build`."
    required: false
    default: ""
  scully-args:
    description: "Additional arguments that get passed to `npm run scully`."
    required: false
    default: ""
runs:
  using: "node16"
  main: "./dist/index.js"
